# Generated by Django 4.0.5 on 2022-07-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('title', models.TextField(max_length=120)),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('F', 'Done'), ('P', 'In Progress'), ('Q', 'Queued')], default='Q', max_length=1)),
            ],
        ),
    ]
